<?php
namespace Modules\Visa\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Booking\Models\Enquiry;
use Modules\Visa\Hook;
use Modules\Visa\Models\Visa;
use Modules\Visa\Models\VisaTerm;
use Modules\Visa\Models\VisaTranslation;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;
use Modules\User\Models\Plan;

class ManageVisaController extends FrontendController
{
    protected $visaClass;
    protected $visaTranslationClass;
    protected $visaTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    protected $enquiryClass;

    public function __construct(Visa $visaClass,VisaTranslation $visaTranslationClass, Location $locationClass,Attributes $attributesClass, VisaTerm $visaTermClass,Booking $bookingClass, Enquiry $enquiryClass)
    {
        parent::__construct();
        $this->locationClass = $locationClass;
        $this->visaClass = $visaClass;
        $this->attributesClass = $attributesClass;
        $this->visaTranslationClass = $visaTranslationClass;
        $this->visaTermClass = $visaTermClass;
        $this->bookingClass = $bookingClass;
        $this->enquiryClass = $enquiryClass;
    }

    public function callAction($method, $parameters)
    {
        if(!Visa::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function manageVisa(Request $request)
    {
        $this->checkPermission('visa_view');
        $user_id = Auth::id();
        $list_tour = $this->visaClass::where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Visas'),
                    'url'  => route('visa.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Manage Visas"),
        ];
        return view('Visa::frontend.manageVisa.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('visa_view');
        $user_id = Auth::id();
        $list_tour = $this->visaClass::onlyTrashed()->where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Visas'),
                    'url'  => route('visa.vendor.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Recovery Visas"),
        ];
        return view('Visa::frontend.manageVisa.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('visa_delete');
        $user_id = Auth::id();
        $query = $this->visaClass::onlyTrashed()->where("author_id", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
            event(new UpdatedServiceEvent($query));

        }
        return redirect(route('visa.vendor.recovery'))->with('success', __('Restore visa success!'));
    }

    public function createVisa(Request $request)
    {
        $this->checkPermission('visa_create');
        $row = new $this->visaClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->visaTranslationClass(),
            'visa_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'visa')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Visas'),
                    'url'  => route('visa.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Visas"),
        ];
        return view('Visa::frontend.manageVisa.detail', $data);
    }


    public function store( Request $request, $id ){
        if(is_demo_mode()){
            return redirect()->back()->with('danger',__("DEMO MODE: can not add data"));
        }
        if($id>0){
            $this->checkPermission('visa_update');
            $row = $this->visaClass::find($id);
            if (empty($row)) {
                return redirect(route('visa.vendor.index'));
            }

            if($row->author_id != Auth::id() and !$this->hasPermission('visa_manage_others'))
            {
                return redirect(route('visa.vendor.index'));
            }
        }else{
            $this->checkPermission('visa_create');
            $row = new $this->visaClass();
            $row->status = "publish";
            if(setting_item("visa_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
            $row->author_id = Auth::id();
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'number',
            'price',
            'sale_price',
            'passenger',
            'gear',
            'baggage',
            'door',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'service_fee',
            'min_day_before_booking',
            'min_day_stays',
            'ical_import_url'
        ];

        $row->fillByAttr($dataKeys,$request->input());

        if(!auth()->user()->checkUserPlan() and $row->status == "publish") {
            return redirect(route('user.plan'));
        }

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            do_action(Hook::AFTER_SAVING,$row,$request);
            if($id > 0 ){
                event(new UpdatedServiceEvent($row));
                return back()->with('success',  __('Visa updated') );
            }else{
                event(new CreatedServicesEvent($row));
                return redirect(route('visa.vendor.edit',['id'=>$row->id]))->with('success', __('Visa created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->visaTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->visaTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->visaTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function editVisa(Request $request, $id)
    {
        $this->checkPermission('visa_update');
        $user_id = Auth::id();
        $row = $this->visaClass::where("author_id", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('visa.vendor.index'))->with('warning', __('Visa not found!'));
        }
        $translation = $row->translate($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'visa_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'visa')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Visas'),
                    'url'  => route('visa.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Visas"),
        ];
        return view('Visa::frontend.manageVisa.detail', $data);
    }

    public function deleteVisa($id)
    {
        $this->checkPermission('visa_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->visaClass::where("author_id", $user_id)->where("id", $id)->withTrashed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->visaClass::where("author_id", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
                event(new UpdatedServiceEvent($query));
            }
        }
        return redirect(route('visa.vendor.index'))->with('success', __('Delete visa success!'));
    }

    public function bulkEditVisa($id , Request $request){
        $this->checkPermission('visa_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->visaClass::where("author_id", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                if(!auth()->user()->checkUserPlan()) {
                    return redirect(route('user.plan'));
                }
                $query->status = "publish";
                break;
        }
        $query->save();
        event(new UpdatedServiceEvent($query));

        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("visa_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();
                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}
